<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "contributory_calculator"
 * Auto generated by Extension Builder 2016-12-08
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Contributory Calculator',
    'description' => 'Extension to calculate contributories in the frontend.',
    'category' => 'plugin',
    'author' => 'Pascal Rinker',
    'author_email' => 'projects@jweiland.net',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.18-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
