services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\ContributoryCalculator\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  JWeiland\ContributoryCalculator\Service\Calculator:
    public: true
